/* ============================================================================
   gen-fixture.mjs — emit harness/fixture.html from the shared probe list.
   ============================================================================
   The fixture is the COMMON artifact: it is (1) the @source purge-guard that
   keeps every tune utility in the reference build, and (2) the DOM the browser
   renders so we can read computed styles. It is generated (never hand-edited)
   so it can never disagree with probes.mjs. Regenerate after editing probes.
   ============================================================================ */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PROBES } from './probes.mjs';

const here = dirname(fileURLToPath(import.meta.url));

function render(p) {
  const cls = p.className ? ` class="${p.className}"` : '';
  const style = ` style="${p.style}"`;
  if (p.capOn === 'firstChild') {
    /* The utility puts margin on every child but the last (& > :not(:last-child)),
       so we give the probe two block children and read the FIRST one's margin. */
    return `<${p.tag}${cls}${style}>` +
      `<b data-cap="${p.id}" style="display:block">a</b>` +
      `<b style="display:block">b</b>` +
      `</${p.tag}>`;
  }
  return `<${p.tag} data-cap="${p.id}"${cls}${style}>&middot;</${p.tag}>`;
}

const body = PROBES.map(render).join('\n  ');
const html = `<!DOCTYPE html>
<!-- GENERATED by harness/gen-fixture.mjs — DO NOT EDIT. Regenerate after changing probes.mjs. -->
<html>
<head><meta charset="utf-8"></head>
<body>
<div id="probes">
  ${body}
</div>
</body>
</html>
`;

const out = join(here, 'fixture.html');
writeFileSync(out, html);
console.log(`wrote ${out}: ${PROBES.length} probes`);
